### ISSUE TITLE
Add sprite sheet to time line using TweenMax.spriteSheet Method

### ISSUE THREAD

**Issue by mubbashar** [spalt08/TweenSprite#2]
Hi,
thanks for such a beautiful and useful plugin :)
TweenMax.spriteSheet( domElement, { 
    width: 818, 
    offsetX: 0,
    offsetY: 2,
    stepX: 201, 
    stepY: 154, 
    count: 12
}, sequenceTime, { delay: 0.1, repeat: -1 });

How can i add this sprite sheet to TimelineMax. so i can pause and start at any given time.
Can you please help me out
thanks!

**Comment by spalt08** [comment]
Hello, mubbashar!
You can just use TimelineMax.add method

``` js
// make a timeline
var tl = new TimelineMax();

tl.add( 
    TweenMax.spriteSheet( domElement, { 
        width: 818, 
        offsetX: 0,
        offsetY: 2,
        stepX: 201, 
        stepY: 154, 
        count: 12
    }, sequenceTime, { delay: 0.1, repeat: -1 });
); // adding animation
```

**Comment by mubbashar** [comment]
ok thanks for your quick response. That works. but the tl.pause( time ) method to pause the tween at particular time is not working as intended. 

http://techesthete.net/mubbashar/animation/

look here. sorry about sprite sheet it is very big and need optimization.

**Comment by spalt08** [comment]
I think it is because you use lots of timelines with similar name. Try to rename you spritesheet timeline different way and pause it.

And why you don't use basics animations with blocs or video? It would be much graceful

**Comment by mubbashar** [comment]
Please check the latest code. i cleaned it up a little bit. but still the same things

And why you don't use basics animations with blocs or video? It would be much graceful

i did not get you. I am new to Tween Library.

**Comment by mubbashar** [comment]
tl.pause() is working . But pausing at particular time let say at 2 seconds is not working.

**Comment by spalt08** [comment]
Is it working now?
